"""create_event_table

Revision ID: a79a033d62bd
Revises:
Create Date: 2023-10-05 18:46:10.915881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79a033d62bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
        sa.Column('user_ip', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
